{% set name = "Flask-Cors" %}
{% set pname = "flask_cors" %}
{% set version = "6.0.2" %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/flask-cors/flask_cors-6.0.2.tar.gz
  sha256: 6e118f3698249ae33e429760db98ce032a8bf9913638d085ca0f4c5534ad2423

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - flask >=0.9
    - six
    - werkzeug >=0.7

test:
  imports:
    - flask_cors

about:
  license: MIT
  home: https://github.com/corydolphin/flask-cors
  license_file: LICENSE
  license_family: MIT
  summary: Cross Origin Resource Sharing ( CORS ) support for Flask
  description: |
    A Flask extension for handling Cross Origin Resource Sharing (CORS), making cross-origin AJAX possible.
  doc_url: http://flask-cors.corydolphin.com/en/latest/
  dev_url: https://github.com/corydolphin/flask-cors

extra:
  recipe-maintainers:
    - knaaptime
