{% set name = "Flask-Cors" %}
{% set pname = "flask_cors" %}
{% set version = "3.0.9" %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bcfc100288c5d1bcb1dbb854babd59beee622ffd321e444b05f24d6d58466b8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask >=0.9
    - six

test:
  imports:
    - flask_cors

about:
  license: MIT
  home: https://github.com/corydolphin/flask-cors
  license_file: LICENSE
  license_family: MIT
  summary: Cross Origin Resource Sharing ( CORS ) support for Flask

  description: |
    A Flask extension for handling Cross Origin Resource Sharing (CORS), making cross-origin AJAX possible.
  doc_url: http://flask-cors.corydolphin.com/en/latest/
  dev_url: https://github.com/corydolphin/flask-cors

extra:
  recipe-maintainers:
    - knaaptime
